Fix ob-julia when the `char` is `nil`.
gcv/julia-snail pull request #106
Opened 2022-08-09 17:45 UTC by MasonProtter

Should fix https://github.com/gcv/julia-snail/issues/99

2022-08-10 04:54 UTC, gcv requested changes
Just a minor nitpick here.

2022-08-10 04:54 UTC, gcv commented on extensions/ob-julia/ob-julia.el
> +  (if char
Looks like this should be a `when`.

2022-08-10 16:34 UTC, MasonProtter commented on extensions/ob-julia/ob-julia.el
> +  (if char
Ah okay, I've switched it to `when`.

2022-08-12 22:48 UTC, merged

2022-08-12 22:49 UTC, gcv commented on extensions/ob-julia/ob-julia.el
> +  (if char
Thanks!