Set configurable resource directory for ob-julia extension
gcv/julia-snail pull request #146
Opened 2024-02-29 10:05 UTC by MasonProtter

This lets users customize where images are saved. By default it's a local hidden folder, but users can set it to e.g. `/tmp/` or whatever if they don't want to keep these images around.

2024-02-29 17:31 UTC, gcv requested changes

2024-02-29 17:31 UTC, gcv commented on extensions/ob-julia/src/ObJulia.jl
> +                        tmp = tempname(mkpath(resource_directory); cleanup=false) * ext
Is using `tempname` still appropriate in this case?

2024-02-29 17:31 UTC, gcv commented on extensions/ob-julia/ob-julia.el
> +(defcustom org-babel-julia-snail-resource-directory "./.ob-julia-snail/"
I'm not sure this configuration option should be in the `org-babel-` namespace. Isn't `julia-snail/ob-julia-resource-directory` more appropriate?

2024-02-29 17:39 UTC, MasonProtter commented on extensions/ob-julia/ob-julia.el
> +(defcustom org-babel-julia-snail-resource-directory "./.ob-julia-snail/"
I was just copying what Jupyter Emacs calls it, but yeah I can change it if you want.

2024-02-29 17:41 UTC, MasonProtter commented on extensions/ob-julia/src/ObJulia.jl
> +                        tmp = tempname(mkpath(resource_directory); cleanup=false) * ext
yep. The `tempname` will make a randonlynamed file in that path.  E.g.:
```julia
julia> tempname(mkpath("./ob-julia-snail.jl"); cleanup=false)
"./ob-julia-snail.jl/jl_kvCpoxEhCd"
```
the `cleanup=false` option will stop julia from erasing it when the session ends.

2024-02-29 20:01 UTC, gcv commented on extensions/ob-julia/ob-julia.el
> +(defcustom org-babel-julia-snail-resource-directory "./.ob-julia-snail/"
Yes, please.

2024-02-29 23:15 UTC, MasonProtter commented on extensions/ob-julia/ob-julia.el
> +(defcustom org-babel-julia-snail-resource-directory "./.ob-julia-snail/"
Done

2024-03-03 15:06 UTC, gcv approved these changes
Looks good to me.

2024-03-03 15:07 UTC, merged