JuliaSnail.jl. add a param addr in function start.
gcv/julia-snail pull request #66
Opened 2021-11-04 03:50 UTC by norci

for #65 .
In the docker container, the listen address should be 0.0.0.0, not localhost, or port can not be published.

2021-11-06 11:18 UTC, norci commented
I used [docker-tramp](https://github.com/emacs-pe/docker-tramp.el) to open files. then julia snail worked perfectly.

I added these custom vars:
```
(custom-set-variables
 '(julia-snail-host "0.0.0.0")
)
```
added a file in the docker compose dir.
`docker-compose.override.yml`
```
version: "3"
services:
  julia:
    ports:
      - 127.0.0.1:10011:10011
    volumes:
      - ${HOME}/.emacs.d/julia-snail/:${HOME}/.emacs.d/julia-snail/:ro
```

I want to make `julia-snail-host` a local var, if the tramp method is "docker", then set its value to "0". But I have no idea about it. Could you tell me how? thanks.

2021-11-06 15:50 UTC, gcv commented
Nice! Please post a complete sample docker compose configuration so I can give this a try.

2021-11-07 03:35 UTC, norci commented
try this
run
`
docker run --name julia-1 --rm -it -p 127.0.0.1:10011:10011 -v ${HOME}/.emacs.d/julia-snail/:${HOME}/.emacs.d/julia-snail/ julia bash
`
then eval
`(docker-container-find-directory "julia-1" "/")`
in buffer `/docker:julia-1:/` run `julia-snail`.

2021-11-09 15:27 UTC, gcv requested changes
This is really good! Exciting to have container Julia support added to Snail. Please go over in-line comments.

2021-11-09 15:27 UTC, gcv commented on julia-snail.el
> +          (format "JuliaSnail.start(%d; addr=\"%s\"); # please wait, time-to-first-plot..." (or julia-snail-remote-port julia-snail-port) julia-snail-host)
What if we do this instead?

```elisp
(format "JuliaSnail.start(%d%s); # please wait, time-to-first-plot..."
        (or julia-snail-remote-port julia-snail-port)
        (if (string-equal "docker" (file-remote-p (buffer-file-name julia-snail--repl-go-back-target) 'method))
            "; addr=\"0.0.0.0\""
          ""))
```

I didn't test very thoroughly, but it seems to work. It lets us eliminate the `julia-snail-host` variable altogether, though perhaps it's valuable for other use cases?

2021-11-10 04:25 UTC, norci commented
thanks for your advise.
I have tested it on local, ssh, docker. it worked.

2021-11-10 14:42 UTC, merged

2021-11-10 14:43 UTC, gcv commented
Thank you for your contribution to Snail! I merged your PR, and added documentation to the CHANGELOG and README files.